"""Canonical workflow taxonomy + free-text inference.

Phase 4 completion — the workflow dimension of the canonical knowledge layer.

The evidence graph stores workflows as verbose free text
("customer service call handling and employee absence reporting"), so exact
matching fails. This module:

  * defines canonical workflow slugs (reusing ``ALL_WORKFLOWS`` from
    ``comparability.py`` — one canonical set, no drift)
  * maps free-text phrases → canonical slugs via exact aliases + an ordered
    keyword table (longest keywords first, deterministic first-match)
  * infers a workflow from arbitrary text (title/problem statement) for
    records that never stored one
  * maps canonical slug → business function (the ``WORKFLOWS`` reverse map)

Mirrors taxonomy.py conventions: deterministic, raw preserved, provenance
attached, unmapped values kept at low confidence (never dropped).
"""

from __future__ import annotations

import re
from typing import Optional

from compass_collector.analysis.comparability import ALL_WORKFLOWS, WORKFLOWS
from compass_collector.organization.taxonomy import NormalizedValue

WORKFLOW_NORMALIZATION_VERSION = "workflow-v1"

# Reverse map: canonical slug → business function.
_FUNCTION_BY_WORKFLOW: dict[str, str] = {
    wf: fn for fn, wfs in WORKFLOWS.items() for wf in wfs
}

_SLUG_RE = re.compile(r"[^a-z0-9]+")
_PAREN_RE = re.compile(r"\([^)]*\)")


def _clean(raw: str) -> str:
    if raw is None:
        return ""
    text = str(raw).strip().lower()
    text = _PAREN_RE.sub(" ", text)
    text = text.replace("_", " ").replace("-", " ").replace("/", " ")
    return re.sub(r"\s+", " ", text).strip()


def workflow_function(slug: Optional[str]) -> Optional[str]:
    """Business function for a canonical workflow slug."""
    return _FUNCTION_BY_WORKFLOW.get(slug or "")


def slugify(raw: str) -> str:
    return _SLUG_RE.sub("_", str(raw or "").strip().lower()).strip("_")


# Exact alias: normalized phrase → canonical slug.
WORKFLOW_ALIASES: dict[str, str] = {
    "invoice processing": "invoice_processing",
    "invoice automation": "invoice_processing",
    "accounts payable": "accounts_payable",
    "accounts receivable": "accounts_receivable",
    "financial close": "financial_reporting",
    "financial reporting": "financial_reporting",
    "expense management": "expense_management",
    "revenue recognition": "revenue_recognition",
    "contract review": "contract_review",
    "contract management": "contract_management",
    "lead qualification": "lead_qualification",
    "proposal generation": "proposal_generation",
    "customer onboarding": "onboarding",
    "employee onboarding": "onboarding",
    "ticketing": "ticketing",
    "helpdesk": "helpdesk",
    "help desk": "helpdesk",
    "call routing": "call_routing",
    "knowledge base": "knowledge_base",
    "self service": "self_service",
    "warehouse management": "warehouse_management",
    "inventory management": "inventory_management",
    "inventory optimization": "inventory_optimization",
    "demand forecasting": "demand_forecasting",
    "supply chain": "supplier_management",
    "supplier management": "supplier_management",
    "order processing": "order_processing",
    "order fulfillment": "order_fulfillment",
    "logistics": "logistics",
    "payroll": "payroll",
    "recruiting": "recruiting",
    "recruitment": "recruiting",
    "procurement": "procurement",
    "purchase order": "purchase_order",
    "spend analysis": "spend_analysis",
    "cloud migration": "cloud_migration",
    "database migration": "database_migration",
    "ci cd": "ci_cd",
    "deployment": "deployment",
    "code review": "code_review",
    "testing": "testing",
    "security operations": "security_operations",
    "incident response": "incident_response",
    "identity management": "identity_management",
    "access management": "access_management",
    "campaign management": "campaign_management",
    "content generation": "content_generation",
    "email marketing": "email_marketing",
    "social media": "social_media",
    "lead scoring": "lead_scoring",
    "personalization": "personalization",
    "analytics reporting": "analytics_reporting",
    "audit": "audit",
    "compliance monitoring": "compliance_monitoring",
    "regulatory reporting": "regulatory_reporting",
    "policy management": "policy_management",
    "data privacy": "data_privacy",
    "risk assessment": "risk_assessment",
    "discovery": "discovery",
    "quality control": "quality_control",
    "scheduling": "scheduling",
    "forecasting": "forecasting",
    "budgeting": "budgeting",
    "reconciliation": "reconciliation",
    "general ledger": "general_ledger",
    "tax preparation": "tax_preparation",
    "fixed assets": "fixed_assets",
    "benefits administration": "benefits_administration",
    "performance management": "performance_management",
    "learning development": "learning_development",
    "employee engagement": "employee_engagement",
    "compliance training": "compliance_training",
    "change management": "change_management",
    "asset management": "asset_management",
    "backup recovery": "backup_recovery",
    "network management": "network_management",
    "capacity planning": "capacity_planning",
    "performance optimization": "performance_optimization",
    "api management": "api_management",
    "requirements management": "requirements_management",
    "roadmap planning": "roadmap_planning",
    "user research": "user_research",
    "a b testing": "a_b_testing",
    "prototyping": "prototyping",
    "user testing": "user_testing",
    "accessibility": "accessibility",
    "design handoff": "design_handoff",
    "literature review": "literature_review",
    "experiment design": "experiment_design",
    "data collection": "data_collection",
    "statistical analysis": "statistical_analysis",
    "publication": "publication",
    "vendor selection": "vendor_selection",
    "contract negotiation": "contract_negotiation",
    "supplier evaluation": "supplier_evaluation",
    "route planning": "scheduling",
    "quality assurance": "quality_assurance",
    "sentiment analysis": "sentiment_analysis",
    "predictive maintenance": "predictive_maintenance",
    "master data management": "master_data_management",
    "revenue cycle management": "revenue_cycle_management",
    "document processing": "document_management",
    "payment processing": "invoice_processing",
    "ach payment processing": "invoice_processing",
    "bill payment processing": "invoice_processing",
    "electronic bill payment": "invoice_processing",
    "transportation management": "logistics",
    "subscription billing": "invoice_processing",
    "sales management": "forecasting",
    "sales order processing": "order_processing",
    "order entry processing": "order_processing",
    "quote processing": "proposal_generation",
    "lead management": "lead_qualification",
    "lead enrichment": "lead_qualification",
    "customer segmentation": "personalization",
    "cart abandonment": "ecommerce",
    "cart abandonment recovery": "ecommerce",
    "medical transcription": "clinical_documentation",
    "medical record summarization": "clinical_documentation",
    "clinical trial data": "data_collection",
    "talent acquisition": "recruiting",
    "mortgage application": "loan_processing",
    "mortgage processing": "loan_processing",
    "loan disbursement": "loan_processing",
    "marketing automation": "campaign_management",
    "workflow automation": "workflow_automation",
    "cost reduction": "cost_optimization",
    "cost savings": "cost_optimization",
    "profit improvement": "cost_optimization",
    "data entry": "document_management",
    "sales compensation": "payroll",
    "incentive compensation": "payroll",
    "succession planning": "performance_management",
    "merger integration": "change_management",
    "acquisition integration": "change_management",
    "restaurant operations": "facilities_management",
    "postoperative recovery": "scheduling",
    "enhanced recovery protocol": "scheduling",
    "percutaneous": "clinical_documentation",
    "population health management": "population_health_management",
    "population health": "population_health_management",
    "data integration": "data_integration",
    "data consolidation": "data_integration",
    "code generation": "code_generation",
    "innovation management": "innovation_management",
    "idea management": "innovation_management",
    "idea crowdsourcing": "innovation_management",
    "appointment booking": "appointment_booking",
    "appointment scheduling": "appointment_booking",
    "fraud detection": "fraud_detection",
    "fraud management": "fraud_detection",
    "fraud prevention": "fraud_detection",
    "customer 360": "customer_360",
    "customer 360 view": "customer_360",
    "retail operations": "retail_operations",
    "retail commerce": "retail_operations",
    "omnichannel retail": "retail_operations",
    "public service delivery": "public_service_delivery",
    "government service delivery": "public_service_delivery",
    "digital transformation": "digital_transformation",
    "cloud cost management": "cloud_cost_management",
    "cloud cost optimization": "cloud_cost_management",
    "manufacturing execution": "manufacturing_execution",
    "production line": "manufacturing_execution",
    "data warehousing": "data_warehousing",
    "equipment maintenance": "equipment_maintenance",
    "contact center": "contact_center",
    "contact centre": "contact_center",
    "business process automation": "workflow_automation",
    "process automation": "workflow_automation",
    "rpa implementation": "workflow_automation",
    "software adoption": "change_management",
    "drug discovery": "literature_review",
    "medical imaging": "clinical_documentation",
    "medical image analysis": "clinical_documentation",
    "threat detection": "security_operations",
    "loyalty program": "personalization",
    "loyalty management": "personalization",
    "email sorting": "email_processing",
    "email routing": "email_processing",
    "customer due diligence": "fraud_detection",
    "anti money laundering": "fraud_detection",
    "process quality improvement": "quality_control",
    "patient diagnosis": "clinical_documentation",
    "treatment planning": "clinical_documentation",
    "mobile ordering": "order_processing",
    "product data management": "data_curation",
    "data catalog": "data_curation",
    "customer lifetime value": "personalization",
    "customer behavior prediction": "personalization",
    "guest service": "call_routing",
    "customer experience management": "customer_journey",
    "customer experience strategy": "customer_journey",
    "customer lifecycle management": "customer_journey",
    "customer lifecycle": "customer_journey",
    "revenue operations": "forecasting",
    "revenue transformation": "forecasting",
    "data reporting": "analytics_reporting",
    "business intelligence": "analytics_reporting",
    "vendor evaluation": "vendor_selection",
    "transportation management system": "logistics",
    "freight management": "logistics",
    "course development": "learning_development",
    "employee productivity": "employee_engagement",
    "offer letter generation": "recruiting",
    "data synchronization": "data_integration",
    "data pipeline": "data_pipeline",
    "agreement management": "contract_management",
    "healthcare operations": "clinical_documentation",
    "healthcare administration": "clinical_documentation",
    "healthcare workflow": "clinical_documentation",
    "healthcare workflow automation": "clinical_documentation",
    "patient experience": "appointment_booking",
    "point of service": "invoice_processing",
    "product innovation": "innovation_management",
    "r and d": "innovation_management",
}

# Ordered keyword → canonical slug. LONGEST keywords first so
# "customer service call handling" hits call_routing before "customer".
WORKFLOW_KEYWORDS: list[tuple[str, str]] = [
    # finance / accounting
    ("invoic", "invoice_processing"),
    ("accounts payable", "accounts_payable"),
    ("accounts receivable", "accounts_receivable"),
    ("financial close", "financial_reporting"),
    ("financial clos", "financial_consolidation"),
    ("financial consolidation", "financial_consolidation"),
    ("consolidation and close", "financial_consolidation"),
    ("financial process", "financial_reporting"),
    ("financial reporting", "financial_reporting"),
    ("month end close", "financial_reporting"),
    ("revenue recognition", "revenue_recognition"),
    ("expense", "expense_management"),
    ("reconcil", "reconciliation"),
    ("general ledger", "general_ledger"),
    ("tax", "tax_preparation"),
    ("payroll", "payroll"),
    ("budget", "budgeting"),
    ("forecast", "forecasting"),
    ("audit", "audit"),
    ("fraud detection", "risk_assessment"),
    ("risk assessment", "risk_assessment"),
    ("risk management", "risk_assessment"),
    ("credit scoring", "credit_scoring"),
    ("credit decision", "credit_scoring"),
    # sales / legal
    ("lead qualif", "lead_qualification"),
    ("lead generation", "lead_qualification"),
    ("proposal", "proposal_generation"),
    ("rfp", "proposal_generation"),
    ("quoting", "proposal_generation"),
    ("ecommerce", "ecommerce"),
    ("e commerce", "ecommerce"),
    ("online shop", "order_processing"),
    ("contract review", "contract_review"),
    ("contract", "contract_management"),
    ("litigation", "discovery"),
    ("legal", "contract_review"),
    ("compliance", "compliance_monitoring"),
    ("regulatory", "regulatory_reporting"),
    ("policy", "policy_management"),
    ("privacy", "data_privacy"),
    ("intellectual property", "intellectual_property"),
    # customer support
    ("customer service call", "call_routing"),
    ("call handling", "call_routing"),
    ("call center", "call_routing"),
    ("inquiry", "call_routing"),
    ("ticket", "ticketing"),
    ("defect", "ticketing"),
    ("helpdesk", "helpdesk"),
    ("help desk", "helpdesk"),
    ("support", "ticketing"),
    ("client relationship", "relationship_management"),
    ("customer relationship", "relationship_management"),
    ("customer care", "call_routing"),
    ("query handling", "call_routing"),
    ("query resolution", "call_routing"),
    ("knowledge management", "knowledge_base"),
    ("knowledge base", "knowledge_base"),
    ("self service", "self_service"),
    ("chatbot", "chat"),
    ("conversational", "chat"),
    ("sentiment", "sentiment_analysis"),
    ("quality assurance", "quality_assurance"),
    ("merchant support", "ticketing"),
    ("claims", "claims_processing"),
    # HR
    ("onboard", "onboarding"),
    ("recruit", "recruiting"),
    ("hiring", "recruiting"),
    ("personnel file", "onboarding"),
    ("hr document", "onboarding"),
    ("benefits", "benefits_administration"),
    ("performance review", "performance_management"),
    ("performance management", "performance_management"),
    ("learning", "learning_development"),
    ("training", "learning_development"),
    ("engagement", "employee_engagement"),
    ("workforce", "employee_engagement"),
    # operations / supply chain
    ("field service", "field_service"),
    ("data curation", "data_curation"),
    ("customer data", "data_curation"),
    ("data pipeline", "data_pipeline"),
    ("collaboration", "team_collaboration"),
    ("erp", "erp_implementation"),
    ("enterprise resource planning", "erp_implementation"),
    ("scm", "scm_implementation"),
    ("supply chain management", "scm_implementation"),
    ("provisioning", "asset_management"),
    ("fault diagnosis", "infrastructure_monitoring"),
    ("warehouse", "warehouse_management"),
    ("inventory", "inventory_management"),
    ("clinical documentation", "clinical_documentation"),
    ("electronic health record", "clinical_documentation"),
    ("email processing", "email_processing"),
    ("document management", "document_management"),
    ("construction document", "document_management"),
    ("pdf extraction", "document_management"),
    ("text extraction", "document_management"),
    ("supply chain", "supplier_management"),
    ("supplier", "supplier_management"),
    ("procure", "procurement"),
    ("purchase order", "purchase_order"),
    ("vendor selection", "vendor_selection"),
    ("spend", "spend_analysis"),
    ("order management", "order_processing"),
    ("order fulfillment", "order_fulfillment"),
    ("fulfillment", "order_fulfillment"),
    ("logistic", "logistics"),
    ("route plan", "scheduling"),
    ("route optimization", "scheduling"),
    ("scheduling", "scheduling"),
    ("dispatch", "scheduling"),
    ("quality control", "quality_control"),
    ("quality management", "quality_control"),
    ("qms", "quality_control"),
    ("online shopping", "order_processing"),
    ("facilities", "facilities_management"),
    # IT / engineering
    ("cloud migration", "cloud_migration"),
    ("migration", "database_migration"),
    ("ai inference", "ai_inference_serving"),
    ("inference serving", "ai_inference_serving"),
    ("model development", "ai_model_development"),
    ("ai model", "ai_model_development"),
    ("machine learning model", "ai_model_development"),
    ("generative ai", "ai_model_development"),
    ("database", "database_migration"),
    ("ci cd", "ci_cd"),
    ("deployment", "deployment"),
    ("code review", "code_review"),
    ("modernization", "application_modernization"),
    ("legacy application", "application_modernization"),
    ("testing", "testing"),
    ("test automation", "testing"),
    ("security", "security_operations"),
    ("incident", "incident_response"),
    ("identity", "identity_management"),
    ("access management", "access_management"),
    ("device provisioning", "asset_management"),
    ("asset", "asset_management"),
    ("infrastructure", "infrastructure_monitoring"),
    ("monitoring", "infrastructure_monitoring"),
    ("backup", "backup_recovery"),
    ("network", "network_management"),
    ("capacity", "capacity_planning"),
    ("performance optim", "performance_optimization"),
    ("api", "api_management"),
    ("mobile app", "prototyping"),
    ("software development", "code_review"),
    ("data pipeline", "data_collection"),
    # marketing / product
    ("campaign", "campaign_management"),
    ("brand campaign", "campaign_management"),
    ("customer journey", "customer_journey"),
    ("journey orchestration", "customer_journey"),
    ("content", "content_generation"),
    ("ai content", "creative_production"),
    ("photo and video editing", "creative_production"),
    ("video edit", "creative_production"),
    ("creative", "creative_production"),
    ("seo", "seo_optimization"),
    ("social media", "social_media"),
    ("email market", "email_marketing"),
    ("lead scoring", "lead_scoring"),
    ("personaliz", "personalization"),
    ("analytics", "analytics_reporting"),
    ("recommendation", "personalization"),
    ("visual search", "personalization"),
    ("product discovery", "user_research"),
    ("user research", "user_research"),
    ("requirements", "requirements_management"),
    ("roadmap", "roadmap_planning"),
    ("a b test", "a_b_testing"),
    ("prototyp", "prototyping"),
    ("user testing", "user_testing"),
    # research
    ("literature", "literature_review"),
    ("experiment", "experiment_design"),
    ("research", "literature_review"),
    ("statistical", "statistical_analysis"),
    # Phase 4 extension — recovered from LLM taxonomy candidates
    ("predictive maintenance", "predictive_maintenance"),
    ("condition based maintenance", "predictive_maintenance"),
    ("master data", "master_data_management"),
    ("revenue cycle", "revenue_cycle_management"),
    ("loan", "loan_processing"),
    ("mortgage", "loan_processing"),
    ("payment process", "invoice_processing"),
    ("bill payment", "invoice_processing"),
    ("subscription billing", "invoice_processing"),
    ("document process", "document_management"),
    ("order process", "order_processing"),
    ("order entry", "order_processing"),
    ("sales order", "order_processing"),
    ("transportation", "logistics"),
    ("lead", "lead_qualification"),
    ("segment", "personalization"),
    ("cart abandon", "ecommerce"),
    ("abandoned cart", "ecommerce"),
    ("talent acqui", "recruiting"),
    ("clinical trial", "data_collection"),
    ("medical record", "clinical_documentation"),
    ("medical transcript", "clinical_documentation"),
    ("marketing automation", "campaign_management"),
    ("marketing camp", "campaign_management"),
    ("compensation process", "payroll"),
    ("succession", "performance_management"),
    ("merger integ", "change_management"),
    ("acquisition integ", "change_management"),
    ("cost reduc", "cost_optimization"),
    ("cost sav", "cost_optimization"),
    ("cost optim", "cost_optimization"),
    ("surgical", "scheduling"),
    # Phase 5 extension — comprehensive unmapped phrase coverage
    ("population health", "population_health_management"),
    ("patient care", "clinical_documentation"),
    ("data integrat", "data_integration"),
    ("data consolid", "data_integration"),
    ("code generat", "code_generation"),
    ("code assist", "code_generation"),
    ("idea manag", "innovation_management"),
    ("innovation manag", "innovation_management"),
    ("crowdsourc", "innovation_management"),
    ("appointment", "appointment_booking"),
    ("booking", "appointment_booking"),
    ("fraud detect", "fraud_detection"),
    ("fraud manag", "fraud_detection"),
    ("fraud prevent", "fraud_detection"),
    ("customer 360", "customer_360"),
    ("360 view", "customer_360"),
    ("retail oper", "retail_operations"),
    ("retail commerc", "retail_operations"),
    ("omnichannel", "retail_operations"),
    ("online retail", "retail_operations"),
    ("e commerce oper", "retail_operations"),
    ("public servic", "public_service_delivery"),
    ("government servic", "public_service_delivery"),
    ("digital transform", "digital_transformation"),
    ("digitalization", "digital_transformation"),
    ("cloud cost", "cloud_cost_management"),
    ("manufactur execut", "manufacturing_execution"),
    ("production line", "manufacturing_execution"),
    ("data warehous", "data_warehousing"),
    ("data ware housing", "data_warehousing"),
    ("equipment maint", "equipment_maintenance"),
    ("predictive maint", "predictive_maintenance"),
    ("contact centre", "contact_center"),
    ("contact center", "contact_center"),
    ("call handling", "call_routing"),
    ("process automat", "workflow_automation"),
    ("business process automat", "workflow_automation"),
    ("software adopt", "change_management"),
    ("adoption", "change_management"),
    ("drug discover", "literature_review"),
    ("medical imag", "clinical_documentation"),
    ("image analysis", "clinical_documentation"),
    ("threat detect", "security_operations"),
    ("intrusion detect", "security_operations"),
    ("loyalty program", "personalization"),
    ("loyalty manag", "personalization"),
    ("email sort", "email_processing"),
    ("email rout", "email_processing"),
    ("aml", "fraud_detection"),
    ("kyc", "fraud_detection"),
    ("sar draft", "fraud_detection"),
    ("customer due diligen", "fraud_detection"),
    ("anti money launder", "fraud_detection"),
    ("process qual", "quality_control"),
    ("quality improv", "quality_control"),
    ("patient diagnos", "clinical_documentation"),
    ("treatment plan", "clinical_documentation"),
    ("mobile order", "order_processing"),
    ("digital order", "order_processing"),
    ("product data", "data_curation"),
    ("data catalog", "data_curation"),
    ("data product", "data_curation"),
    ("lifetime value", "personalization"),
    ("behavior predict", "personalization"),
    ("customer predict", "personalization"),
    ("guest servic", "call_routing"),
    ("customer experienc", "customer_journey"),
    ("customer engag", "customer_journey"),
    ("customer journ", "customer_journey"),
    ("customer lifecycle", "customer_journey"),
    ("revenue oper", "forecasting"),
    ("revenue transform", "forecasting"),
    ("sales operation", "forecasting"),
    ("report generat", "analytics_reporting"),
    ("data report", "analytics_reporting"),
    ("business intellig", "analytics_reporting"),
    ("vendor evalu", "vendor_selection"),
    ("vendor select", "vendor_selection"),
    ("tms ", "logistics"),
    ("transportation management", "logistics"),
    ("freight", "logistics"),
    ("parcel sort", "logistics"),
    ("parts distribut", "logistics"),
    ("car pool", "logistics"),
    ("carpool", "logistics"),
    ("course develop", "learning_development"),
    ("training program", "learning_development"),
    ("employee productiv", "employee_engagement"),
    ("workforce productiv", "employee_engagement"),
    ("voter reg", "public_service_delivery"),
    ("election process", "public_service_delivery"),
    ("loss prevent", "risk_assessment"),
    ("store layout", "facilities_management"),
    ("member experienc", "personalization"),
    ("guest experi", "personalization"),
    ("offer letter", "recruiting"),
    ("hiring", "recruiting"),
    ("data sync", "data_integration"),
    ("data synchron", "data_integration"),
    ("streaming pipelin", "data_pipeline"),
    ("data pipelin", "data_pipeline"),
    ("low latency", "data_pipeline"),
    ("real time data", "data_pipeline"),
    ("agreement manag", "contract_management"),
    ("software licens", "contract_management"),
    ("rpa implementation", "workflow_automation"),
    ("rpa", "workflow_automation"),
    ("robotic process", "workflow_automation"),
    ("medical record", "clinical_documentation"),
    ("ehr", "clinical_documentation"),
    ("electronic health", "clinical_documentation"),
    ("clinical data", "clinical_documentation"),
    ("healthcare oper", "clinical_documentation"),
    ("healthcare administr", "clinical_documentation"),
    ("healthcare workflow", "clinical_documentation"),
    ("patient experienc", "appointment_booking"),
    ("pos collect", "invoice_processing"),
    ("point of service", "invoice_processing"),
    ("point of sale", "invoice_processing"),
    ("product innov", "innovation_management"),
    ("r&d", "innovation_management"),
    ("research and development", "innovation_management"),
]

_ALIAS_LOOKUP: dict[str, str] = {_clean(k): v for k, v in WORKFLOW_ALIASES.items()}


def _best_keyword_match(cleaned: str) -> Optional[tuple[str, float]]:
    """Earliest keyword occurrence wins; ties break to the longest keyword."""
    best: Optional[tuple[tuple, str]] = None
    for keyword, slug in WORKFLOW_KEYWORDS:
        idx = cleaned.find(keyword)
        if idx >= 0:
            key = (idx, -len(keyword))
            if best is None or key < best[0]:
                best = (key, slug)
    if best:
        return best[1], 0.6
    return None


def normalize_workflow(raw: str) -> NormalizedValue:
    """Normalize a free-text workflow string onto a canonical slug."""
    if not raw or not str(raw).strip():
        return NormalizedValue(raw="", value="", source="workflow_taxonomy", confidence=0.0,
                               version=WORKFLOW_NORMALIZATION_VERSION)
    raw_s = str(raw).strip()
    cleaned = _clean(raw_s)

    canonical = _ALIAS_LOOKUP.get(cleaned)
    if canonical:
        return NormalizedValue(raw=raw_s, value=canonical, source="workflow_taxonomy",
                               method="explicit", confidence=1.0,
                               version=WORKFLOW_NORMALIZATION_VERSION)

    matched = _best_keyword_match(cleaned)
    if matched:
        slug, conf = matched
        return NormalizedValue(raw=raw_s, value=slug, source="workflow_taxonomy",
                               method="inferred", confidence=conf,
                               version=WORKFLOW_NORMALIZATION_VERSION)

    # Unmapped — keep the slugified raw value (never drop).
    return NormalizedValue(raw=raw_s, value=slugify(raw_s), source="workflow_taxonomy",
                           method="inferred", confidence=0.3,
                           version=WORKFLOW_NORMALIZATION_VERSION)


def infer_workflow(text: Optional[str]) -> NormalizedValue:
    """Infer a workflow from arbitrary text (title/problem statement)."""
    if not text:
        return NormalizedValue(raw="", value="", source="workflow_taxonomy", confidence=0.0,
                               version=WORKFLOW_NORMALIZATION_VERSION)
    cleaned = _clean(text)
    if not cleaned:
        return infer_workflow(None)
    matched = _best_keyword_match(cleaned)
    if matched:
        slug, _conf = matched
        return NormalizedValue(raw=text[:200], value=slug, source="workflow_taxonomy",
                               method="inferred", confidence=0.5,
                               version=WORKFLOW_NORMALIZATION_VERSION)
    return NormalizedValue(raw=text[:200], value="uncategorized", source="workflow_taxonomy",
                           method="inferred", confidence=0.2,
                           version=WORKFLOW_NORMALIZATION_VERSION)


def is_canonical(slug: Optional[str]) -> bool:
    return slug in ALL_WORKFLOWS
